//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teretana.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teretana.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DODAJ.
        /// </summary>
        public static string Add_btn
        {
            get
            {
                return ResourceManager.GetString("Add_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja:.
        /// </summary>
        public static string Birth_date_lbl
        {
            get
            {
                return ResourceManager.GetString("Birth_date_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grad:.
        /// </summary>
        public static string City_lbl
        {
            get
            {
                return ResourceManager.GetString("City_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dana do isteka:.
        /// </summary>
        public static string Days_lbl
        {
            get
            {
                return ResourceManager.GetString("Days_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OBRIŠI.
        /// </summary>
        public static string Delete_btn
        {
            get
            {
                return ResourceManager.GetString("Delete_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IZMIJENI.
        /// </summary>
        public static string Edit_btn
        {
            get
            {
                return ResourceManager.GetString("Edit_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email_lbl
        {
            get
            {
                return ResourceManager.GetString("Email_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info_header
        {
            get
            {
                return ResourceManager.GetString("Info_header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JMBG:.
        /// </summary>
        public static string Jmbg_lbl
        {
            get
            {
                return ResourceManager.GetString("Jmbg_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PRIJAVA.
        /// </summary>
        public static string Login_btn
        {
            get
            {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ODJAVA.
        /// </summary>
        public static string Logout_btn
        {
            get
            {
                return ResourceManager.GetString("Logout_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Član.
        /// </summary>
        public static string Member_header
        {
            get
            {
                return ResourceManager.GetString("Member_header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Članovi:.
        /// </summary>
        public static string Members_lbl
        {
            get
            {
                return ResourceManager.GetString("Members_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Članarina.
        /// </summary>
        public static string Membership_header
        {
            get
            {
                return ResourceManager.GetString("Membership_header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Name_lbl
        {
            get
            {
                return ResourceManager.GetString("Name_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NOVA.
        /// </summary>
        public static string New_btn
        {
            get
            {
                return ResourceManager.GetString("New_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uplatio:.
        /// </summary>
        public static string Paid_lbl
        {
            get
            {
                return ResourceManager.GetString("Paid_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password_lbl
        {
            get
            {
                return ResourceManager.GetString("Password_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to POVUCI.
        /// </summary>
        public static string Revoke_btn
        {
            get
            {
                return ResourceManager.GetString("Revoke_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SAČUVAJ.
        /// </summary>
        public static string Save_btn
        {
            get
            {
                return ResourceManager.GetString("Save_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string Start_btn
        {
            get
            {
                return ResourceManager.GetString("Start_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Započni novi trening.
        /// </summary>
        public static string Start_lbl
        {
            get
            {
                return ResourceManager.GetString("Start_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string Stop_btn
        {
            get
            {
                return ResourceManager.GetString("Stop_btn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string Surname
        {
            get
            {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treninzi.
        /// </summary>
        public static string Trainings_header
        {
            get
            {
                return ResourceManager.GetString("Trainings_header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Username_lbl
        {
            get
            {
                return ResourceManager.GetString("Username_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vrijedi do:.
        /// </summary>
        public static string Valid_lbl
        {
            get
            {
                return ResourceManager.GetString("Valid_lbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DOBRO DOŠLI.
        /// </summary>
        public static string Welcome_lbl
        {
            get
            {
                return ResourceManager.GetString("Welcome_lbl", resourceCulture);
            }
        }
        public static string Date_header
        {
            get
            {
                return ResourceManager.GetString("Date_header", resourceCulture);
            }
        }
        public static string From_header
        {
            get
            {
                return ResourceManager.GetString("From_header", resourceCulture);
            }
        }
        public static string Until_header
        {
            get
            {
                return ResourceManager.GetString("Until_header", resourceCulture);
            }
        }
        public static string Employees_lbl
        {
            get
            {
                return ResourceManager.GetString("Employees_lbl", resourceCulture);
            }
        }


        public static string Employee_info_header
        {
            get
            {
                return ResourceManager.GetString("Employee_info_header", resourceCulture);
            }
        }
        public static string IsAdmin_cb
        {
            get
            {
                return ResourceManager.GetString("IsAdmin_cb", resourceCulture);
            }
        }
        public static string Employment_info_header
        {
            get
            {
                return ResourceManager.GetString("Employment_info_header", resourceCulture);
            }
        }
        public static string Employment_date_lbl
        {
            get
            {
                return ResourceManager.GetString("Employment_date_lbl", resourceCulture);
            }
        }
        public static string Salary_lbl
        {
            get
            {
                return ResourceManager.GetString("Salary_lbl", resourceCulture);
            }
        }
        public static string Contract_duration_lbl
        {
            get
            {
                return ResourceManager.GetString("Contract_duration_lbl", resourceCulture);
            }
        }

        public static string Insert_new_member_err
        {
            get
            {
                return ResourceManager.GetString("Insert_new_member_err", resourceCulture);
            }
        }
        public static string Delete_err
        {
            get
            {
                return ResourceManager.GetString("Delete_err", resourceCulture);
            }
        }
        public static string Continue_prompt
        {
            get
            {
                return ResourceManager.GetString("Continue_prompt", resourceCulture);
            }
        }
        public static string Gym_name
        {
            get
            {
                return ResourceManager.GetString("Gym_name", resourceCulture);
            }
        }

        public static string Succesfull_deletion
        {
            get
            {
                return ResourceManager.GetString("Succesfull_deletion", resourceCulture);
            }
        }
        public static string Existing_membership
        {
            get
            {
                return ResourceManager.GetString("Existing_membership", resourceCulture);
            }
        }

        public static string Select_member
        {
            get
            {
                return ResourceManager.GetString("Select_member", resourceCulture);
            }
        }
        public static string Create_membership
        {
            get
            {
                return ResourceManager.GetString("Create_membership", resourceCulture);
            }
        }
        public static string Training_start_error
        {
            get
            {
                return ResourceManager.GetString("Training_start_error", resourceCulture);
            }
        }

        public static string Training_stop_err
        {
            get
            {
                return ResourceManager.GetString("Training_stop_err", resourceCulture);
            }
        }
        public static string Training_ended_errr
        {
            get
            {
                return ResourceManager.GetString("Training_ended_errr", resourceCulture);
            }
        }
        public static string Select_training
        {
            get
            {
                return ResourceManager.GetString("Select_training", resourceCulture);
            }
        }
        public static string Image_set_error
        {
            get
            {
                return ResourceManager.GetString("Image_set_error", resourceCulture);
            }
        }
        public static string Image_set_succesfully
        {
            get
            {
                return ResourceManager.GetString("Image_set_succesfully", resourceCulture);
            }
        }
        public static string Unsuported_format
        {
            get
            {
                return ResourceManager.GetString("Unsuported_format", resourceCulture);
            }
        }
        
    }
}
